/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets list of applications. */
        get: operations["applications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets an application. */
        get: operations["applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/apply/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates an application. */
        post: operations["applications_apply_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Deletes an application. */
        post: operations["applications_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/get/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets an application. */
        get: operations["applications_get_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restores an application. */
        post: operations["applications_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets games list. */
        get: operations["games_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a games. */
        get: operations["games_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/characters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets games characters. */
        get: operations["games_characters_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets games groups. */
        get: operations["games_groups_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets games tags. */
        get: operations["games_tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all the notifications. */
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/viewed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Set notification status as viewed. */
        post: operations["notifications_viewed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets questions list. */
        get: operations["questions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a question. */
        get: operations["questions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session_retrieve"];
        put?: never;
        post: operations["session_create"];
        delete: operations["session_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logs user in. */
        post: operations["token_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logs user out. */
        post: operations["token_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/like_character/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Likes or dislikes a character. */
        post: operations["users_like_character_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Makes an action for current user based on query action. */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/mg/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieves the list of master group users. */
        get: operations["users_mg_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieves the list of players for a games by alias. */
        get: operations["users_players_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new user. */
        post: operations["users_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/telegram_link/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Users viewset. */
        post: operations["users_telegram_link_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/update_me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Makes an action for current user based on query action. */
        put: operations["users_update_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Application serializer. */
        ApplicationPrivate: {
            readonly id: number;
            /** Игра */
            readonly game: number;
            readonly character: components["schemas"]["Character"] | null;
            /** Взнос */
            readonly price: number | null;
            /** Оплачено */
            readonly payed: number;
            /** @description Gets application answers. */
            readonly answers: {
                values: {
                    [key: string]: (string | string[] | string[][]) | null;
                };
                unfilled: number[];
            };
            /** Статус */
            readonly status: components["schemas"]["StatusEnum"];
        };
        /** @description Application serializer. */
        ApplicationPublic: {
            readonly id: number;
            /** Игра */
            readonly game: number;
            /** Персонаж */
            readonly character: number | null;
            /** Статус */
            readonly status: components["schemas"]["StatusEnum"];
        };
        /** @description Character serializer. */
        Character: {
            readonly id: number;
            /** Имя */
            readonly name: string;
            /** Имя (Англ) */
            readonly name_eng: string | null;
            /** Никнейм */
            readonly alias: string;
            /** Описание */
            readonly description: string | null;
            /** Format: uri */
            readonly image: string | null;
            readonly player: components["schemas"]["UserPublic"] | null;
            readonly tags: components["schemas"]["Tag"][];
        };
        CharacterLikeRequest: {
            game_alias: string;
            character_id: number;
            like: boolean;
        };
        /** @description Game serializer. */
        Game: {
            readonly id: number;
            /** Алиас */
            readonly alias: string;
            /** Название */
            readonly title: string;
            /** Место */
            readonly location: string | null;
            /** Описание */
            readonly description: string | null;
            /**
             * Начало
             * Format: date-time
             */
            readonly start: string | null;
            /**
             * Конец
             * Format: date-time
             */
            readonly end: string | null;
            /** Год */
            readonly year: number | null;
            /** Короткое описание */
            readonly short_description: string | null;
            readonly vk: string | null;
            readonly tg: string | null;
            /** Прием заявок открыт */
            readonly open_applications: boolean;
            /** Сетка открыта */
            readonly open_character_list: boolean;
            readonly player_count: number;
        };
        GameAliasRequest: {
            game_alias: string;
        };
        /** @description Group serializer. */
        Group: {
            readonly id: number;
            /** Порядковый номер */
            readonly order: number;
            /** Название */
            readonly name: string;
            /** Алиас */
            readonly alias: string | null;
            /** Секретная */
            readonly hidden: boolean;
            /** Семья */
            readonly family: boolean;
            /** Описание */
            readonly description: string | null;
            /** Игра */
            readonly game: number | null;
            /** Родительская фракция */
            readonly parent: number | null;
            readonly characters: components["schemas"]["Character"][];
            readonly members: components["schemas"]["Character"][];
            readonly subgroups: components["schemas"]["Group"][];
        };
        /** @description Notification model serializer. */
        Notification: {
            readonly user: number;
            readonly mailing: number | null;
            readonly viewed: boolean;
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        /** @description Question serializer. */
        Question: {
            readonly id: number;
            /** Вопрос */
            readonly title: string;
            /** Описание */
            readonly description: string | null;
            /** Тип */
            readonly type: components["schemas"]["TypeEnum"];
            readonly choices: (string[] | string[][]) | null;
            /** Порядковый номер */
            readonly order: number;
            /** Обязательный */
            readonly required: boolean;
        };
        /** @description User creation serializer. */
        RegistrationToken: {
            /** Format: email */
            email: string;
            /** Name */
            first_name: string;
            /** Surname */
            last_name: string;
            /** Никнейм */
            username: string;
            readonly auth_token: string;
        };
        Session: {
            readonly user: components["schemas"]["UserPrivate"] | null;
            readonly csrfToken: string;
        };
        Status: {
            status: string;
        };
        /**
         * @description * `pending` - Подана
         *     * `discussing` - Обсуждается
         *     * `confirmed` - Принята
         *     * `declined` - Отклонена
         *     * `deleted` - Удалена
         * @enum {string}
         */
        StatusEnum: "pending" | "discussing" | "confirmed" | "declined" | "deleted";
        /** @description Tag serializer. */
        Tag: {
            readonly id: number;
            /** Название */
            readonly name: string;
            /** Цвет */
            readonly color: string;
        };
        TelegramLink: {
            code: string;
            expires_in: number;
            /** Format: uri */
            url: string;
        };
        /** @description Token serializer. */
        Token: {
            auth_token: string;
        };
        /** @description Token create serializer. */
        TokenCreateRequest: {
            password: string;
            login_field: string;
        };
        /**
         * @description * `line` - Строка
         *     * `paragraph` - Абзац
         *     * `single_choice` - Одиночный выбор
         *     * `multiple_choice` - Множественный выбор
         *     * `scale` - Шкала
         *     * `matrix` - Сетка
         *     * `matrix_checkbox` - Сетка флажков
         * @enum {string}
         */
        TypeEnum: "line" | "paragraph" | "single_choice" | "multiple_choice" | "scale" | "matrix" | "matrix_checkbox";
        /** @description User creation serializer. */
        UserCreateRequest: {
            /** Format: email */
            email: string;
            /** Name */
            first_name: string;
            /** Surname */
            last_name: string;
            /** Никнейм */
            username: string;
            password: string;
        };
        /** @description Serializes for /me route. */
        UserPrivate: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            /** Никнейм */
            readonly username: string;
            /** Name */
            readonly first_name: string;
            /** Surname */
            readonly last_name: string;
            /** Format: uuid */
            readonly uuid: string;
            /** @description Gets user mg status. */
            readonly mg: boolean;
            readonly phone: string | null;
            readonly vk: string | null;
            /** @description Gets users telegram username. */
            readonly telegram: string | null;
            /** Format: date-time */
            readonly created_at: string | null;
            /**
             * Picture
             * Format: uri
             */
            readonly avatar: string | null;
            readonly applications: {
                [key: string]: components["schemas"]["ApplicationPublic"];
            };
            readonly likes: number[];
            readonly vk_public: boolean;
            readonly tg_public: boolean;
        };
        /** @description Only these profile fields may be changed through the SPA. */
        UserProfileUpdateRequest: {
            /** Никнейм */
            username: string;
            /** Name */
            first_name: string;
            /** Surname */
            last_name: string;
            phone?: string | null;
            /** Format: binary */
            avatar?: string | null;
            vk?: string | null;
            vk_public?: boolean;
            tg_public?: boolean;
        };
        /** @description Explicit public profile; never inherit private profile fields. */
        UserPublic: {
            /** Никнейм */
            readonly username: string;
            /** Name */
            readonly first_name: string;
            /** Surname */
            readonly last_name: string;
            /**
             * Picture
             * Format: uri
             */
            readonly avatar: string | null;
            /** @description Gets users vk username. */
            readonly vk: string | null;
            readonly telegram: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_list: {
        parameters: {
            query?: {
                game_alias?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"][];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Заявка. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"];
                };
            };
        };
    };
    applications_apply_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    game_alias: string;
                } & {
                    [key: string]: (string | string[] | string[][]) | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"];
                };
            };
        };
    };
    applications_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameAliasRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GameAliasRequest"];
                "multipart/form-data": components["schemas"]["GameAliasRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"];
                };
            };
        };
    };
    applications_get_retrieve: {
        parameters: {
            query: {
                game_alias: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"] | Record<string, never>;
                };
            };
        };
    };
    applications_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameAliasRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GameAliasRequest"];
                "multipart/form-data": components["schemas"]["GameAliasRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrivate"];
                };
            };
        };
    };
    games_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    games_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game alias or numeric ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
        };
    };
    games_characters_list: {
        parameters: {
            query: {
                game_alias: string;
                search?: string;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    games_groups_list: {
        parameters: {
            query: {
                game_alias: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    games_tags_list: {
        parameters: {
            query: {
                game_alias: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    notifications_viewed_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    questions_list: {
        parameters: {
            query?: {
                game_alias?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
        };
    };
    questions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Вопрос. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenCreateRequest"];
                "multipart/form-data": components["schemas"]["TokenCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    session_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreateRequest"];
                "multipart/form-data": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    token_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenCreateRequest"];
                "multipart/form-data": components["schemas"]["TokenCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    token_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_like_character_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterLikeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CharacterLikeRequest"];
                "multipart/form-data": components["schemas"]["CharacterLikeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_mg_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
        };
    };
    users_players_list: {
        parameters: {
            query: {
                game_alias: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
        };
    };
    users_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreateRequest"];
                "multipart/form-data": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationToken"];
                };
            };
        };
    };
    users_telegram_link_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLink"];
                };
            };
        };
    };
    users_update_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProfileUpdateRequest"];
                "multipart/form-data": components["schemas"]["UserProfileUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
        };
    };
}
