# Generated by Django 4.2.6 on 2023-10-24 11:11

from django.db import migrations, models
import mixins.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('locales', mixins.fields.ChoiceArrayField(base_field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('it', 'Italian'), ('ro', 'Romanian'), ('hu', 'Hungarian'), ('de', 'German'), ('uk', 'Ukrainian'), ('fr', 'French'), ('si', 'Slovenian'), ('es', 'Spanish'), ('tr', 'Turkish'), ('pt', 'Portuguese'), ('cs', 'Czech')], default='en', max_length=2, verbose_name='locale'), default=[], size=None)),
                ('entry_level', models.IntegerField(choices=[(0, 'Free'), (1, 'Camp 1'), (2, 'Camp 2'), (3, 'Camp 3'), (4, 'Camp 4'), (5, 'Energy 1'), (6, 'Energy 2'), (7, 'Energy 3'), (8, 'Energy 4'), (9, 'Energy 5'), (10, 'Energy 6'), (11, 'Energy 7'), (12, 'Energy 8'), (13, 'Energy 9'), (14, 'Energy 10'), (15, 'Energy 11'), (16, 'Energy 12')], default=0, verbose_name='entry level')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mailing/images/', verbose_name='image')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('telegram', models.BooleanField(default=True, verbose_name='telegram')),
                ('email', models.BooleanField(default=False, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('telegram', models.SmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Success'), (2, 'Cancelled'), (3, 'Timeout'), (4, 'NetworkError'), (5, 'BadRequest'), (6, 'TelegramConfl'), (7, 'TokenError')], default=0)),
                ('email_status', models.SmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Success'), (2, 'Cancelled'), (3, 'Timeout'), (4, 'NetworkError'), (5, 'BadRequest'), (6, 'TelegramConfl'), (7, 'TokenError')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('key', models.CharField(default='', max_length=30, verbose_name='key')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('telegram', models.SmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Success'), (2, 'Cancelled'), (3, 'Timeout'), (4, 'NetworkError'), (5, 'BadRequest'), (6, 'TelegramConfl'), (7, 'TokenError')], default=0)),
                ('viewed', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('code', models.CharField(blank=True, max_length=250, null=True, verbose_name='code')),
                ('username', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='first name')),
                ('chat_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='chat')),
                ('settings', models.JSONField(blank=True, default={'group': {'ActivateMatrixNotification': True, 'ArenaNotification': True, 'LostProfitNotification': False, 'MatrixBonusNotification': True, 'MatrixCompletedNotification': True, 'NewCloneNotification': True, 'ProfitNotification': True, 'ReSubscriptionNotification': True, 'ReferalBonusNotification': True, 'SubscriptionNotification': True, 'WithdrawNotification': True}, 'personal': {'ActivateMatrixNotification': True, 'ArenaNotification': True, 'LostProfitNotification': True, 'MatrixBonusNotification': True, 'MatrixCompletedNotification': True, 'NewCloneNotification': True, 'ProfitNotification': True, 'ReSubscriptionNotification': True, 'ReferalBonusNotification': True, 'SubscriptionNotification': True, 'WithdrawNotification': True}, 'team': {'ActivateMatrixNotification': False, 'ArenaNotification': False, 'LostProfitNotification': False, 'MatrixBonusNotification': False, 'MatrixCompletedNotification': False, 'NewCloneNotification': False, 'ProfitNotification': True, 'ReSubscriptionNotification': True, 'ReferalBonusNotification': False, 'SubscriptionNotification': True, 'WithdrawNotification': False}}, verbose_name='settings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
