# Generated by Django 5.1.1 on 2024-11-10 13:49

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mailing/images/', verbose_name='image')),
                ('ready', models.BooleanField(default=False, verbose_name='ready')),
                ('time', models.DateTimeField(db_index=True, verbose_name='time')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notificatio_created_a2844a_brin')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('viewed', models.BooleanField(blank=True, default=False)),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.mailing', verbose_name='mailing')),
            ],
        ),
    ]
