# Generated by Django 4.2.6 on 2023-10-24 11:11

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='mailingrecipient',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.mailing'),
        ),
        migrations.AddField(
            model_name='mailingrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notificatio_created_a2844a_brin'),
        ),
        migrations.AddIndex(
            model_name='chatdata',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notificatio_created_6b5031_brin'),
        ),
        migrations.AddIndex(
            model_name='telegram',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notificatio_created_da65b0_brin'),
        ),
        migrations.AddIndex(
            model_name='mailingrecipient',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notificatio_created_dc1002_brin'),
        ),
    ]
