# Generated by Django 5.1.1 on 2024-11-10 13:49

import django.contrib.auth.models
import django.contrib.postgres.indexes
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='surname')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='picture')),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Country')),
                ('country_iso', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Country ISO code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None)),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin')),
                ('email_active', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='telegram_chat_id')),
                ('telegram_username', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='telegram_username')),
                ('instagram', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='instagram')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='users_user_created_94847f_brin')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
