# Generated by Django 5.1.1 on 2024-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='vk'),
        ),
    ]
