# Generated by Django 5.0.3 on 2024-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='telegram'),
        ),
    ]
