# Generated by Django 5.1.1 on 2024-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='surname'),
        ),
    ]
