# Generated by Django 4.2.6 on 2023-11-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merchant_p2p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixrequest',
            name='refer',
        ),
        migrations.RemoveField(
            model_name='matrixrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Matrix',
        ),
        migrations.DeleteModel(
            name='MatrixRequest',
        ),
    ]
