# Generated by Django 5.1.1 on 2024-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_public',
            field=models.BooleanField(default=True, verbose_name='tg_public'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_public',
            field=models.BooleanField(default=True, verbose_name='vk_public'),
        ),
    ]
