# Generated by Django 4.2.6 on 2023-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_matrixrequest_refer_remove_matrixrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='num',
            field=models.IntegerField(choices=[(0, '0'), (10, '1'), (20, '2'), (30, '3'), (40, '4'), (50, '5'), (60, '6'), (70, '7'), (80, '8'), (90, '9'), (100, '10')], default=0, verbose_name='num'),
        ),
    ]
