name: some-people-prod


networks:
  default-tier:
    driver: bridge


x-backend-base: &backend_base
  image: some-people.prod.backend
  restart: always
  build:
    context: ..
    dockerfile: ./docker/images/backend.Dockerfile
  env_file: ../backend/.env
  working_dir: /app
  volumes:
    - ../backend:/app
  networks:
    - default-tier

x-frontend-base: &frontend_base
  image: some-people.prod.frontend
  restart: always
  build:
    context: ..
    dockerfile: ./docker/images/frontend.Dockerfile
  working_dir: /app
  volumes:
    - ../frontend:/app/
  networks:
    - default-tier

x-container-user: &container_user
  user: "1001:1001"
  group_add:
    - root


services:

  postgresql:
    <<: [ *container_user ]
    image: 'bitnami/postgresql:15'
    restart: always
    env_file: ../backend/.env
    # ports:
    #   - "8432:5432"
    networks:
      - default-tier
    volumes:
      - ./postgres/data:/bitnami/postgresql/

  api:
    <<: [ *backend_base, *container_user ]
    depends_on:
      - postgresql
    command:
      - |
        python manage.py runserver 0:8000
    ports:
      - "8101:8000"


  bot:
    <<: [ *backend_base ]
    restart: always
    depends_on:
      - postgresql
    command:
      - |
        python bot/bot.py


  builder.frontend:
    <<: [ *frontend_base, *container_user ]
    restart: "no"
    profiles:
      - build
    environment:
      - YARN_CACHE_FOLDER=/app/.yarn-cache
      - YARN_GLOBAL_FOLDER=/app/.yarn-global
    command:
      - |
        # yarn
        yarn build
        rm -rf dist
        mv dist_tmp dist
