server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 10m;

    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~ ^/(api|admin|ckeditor)/ {
        proxy_pass http://preview-api:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Cache-Control "no-store" always;
    }
    location /staticfiles/ {
        alias /preview-static/;
    }
    location /media/ {
        alias /preview-media/;
    }
}
