import { test, expect } from '@playwright/test'

test.skip(!process.env.LIVE_API, 'Requires the disposable Django/PostgreSQL browser-test stack.')
test('Swagger renders the generated API contract', async ({ page }) => {
  await page.goto('/api/docs/')
  await expect(page.getByRole('heading', { name: /Some People API/ })).toBeVisible()
  await expect(page.locator('.opblock-summary-path[data-path="/api/games/characters/"]')).toBeVisible()
  await expect(page.getByText('Failed to load API definition.')).toHaveCount(0)
})

test('real Django session, application, questionnaire, profile, and logout', async ({ page, context, isMobile }) => {
  const suffix = test.info().project.name + '-' + Date.now()
  const password = '  browser-test-password-123  '
  await page.goto('/sign-up?next=/account/frostpunk/application')
  await page.getByLabel('Имя', { exact: true }).fill('Synthetic')
  await page.getByLabel('Фамилия', { exact: true }).fill('Player')
  await page.getByLabel('Никнейм', { exact: true }).fill(suffix)
  await page.getByLabel('Email', { exact: true }).fill(suffix + '@example.invalid')
  await page.getByLabel('Пароль', { exact: true }).fill(password)
  await page.getByLabel('Повторите пароль').fill(password)
  await page.getByRole('button', { name: 'Зарегистрироваться' }).click()
  await expect(page.getByRole('heading', { name: 'Заявка не подана' })).toBeVisible()
  const cookies = await context.cookies()
  expect(cookies.find(cookie => cookie.name === 'sessionid')?.httpOnly).toBe(true)
  await page.getByRole('button', { name: 'Подать заявку' }).click()
  await expect(page.getByRole('heading', { name: 'Заявка подана' })).toBeVisible()
  await page.locator('.account-content').getByRole('link', { name: 'Опросник', exact: true }).click()
  await page.getByLabel('frostpunk line *', { exact: true }).fill('A real saved answer')
  await expect(page.getByText('Все изменения сохранены.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('frostpunk line *', { exact: true })).toHaveValue('A real saved answer')
  if (isMobile) await page.getByRole('button', { name: 'Меню кабинета' }).click()
  await page.getByRole('link', { name: 'Настройки', exact: true }).click()
  await page.getByRole('checkbox', { name: 'ВКонтакте' }).uncheck()
  await page.getByRole('checkbox', { name: 'Телеграм', exact: true }).uncheck()
  await page.getByLabel('Аватар', { exact: true }).setInputFiles({
    name: 'avatar.png', mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aVkUAAAAASUVORK5CYII=', 'base64'),
  })
  await expect(page.getByLabel('Предпросмотр аватара')).toBeVisible()
  await page.getByLabel('Масштаб', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Сохранить профиль' }).click()
  await expect(page.getByText('Профиль сохранён.')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'ВКонтакте' })).not.toBeChecked()
  await expect(page.getByAltText('Ваш аватар')).toHaveAttribute('src', /\/media\/users\/avatars\//)
  await page.goto('/game/frostpunk/roles')
  await expect(page.getByText('Hidden character')).toHaveCount(0)
  await page.getByRole('button', { name: 'В избранное: Инженер', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Убрать из избранного: Инженер' })).toBeVisible()
  await page.getByRole('link', { name: 'Личный кабинет', exact: true }).click()
  if (isMobile) await page.getByRole('button', { name: 'Меню кабинета' }).click()
  await page.getByRole('link', { name: 'Выйти', exact: true }).click()
  await page.getByRole('button', { name: 'Выйти', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Войти', exact: true })).toBeVisible()
  await page.goto('/account/frostpunk/application')
  await expect(page).toHaveURL(/sign-in/)
  await page.getByLabel('Email или никнейм').fill(suffix + '@example.invalid')
  await page.getByLabel('Пароль', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Заявка подана', exact: true })).toBeVisible()
})
