# Generated by Django 5.1.1 on 2024-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Подана'), ('discussing', 'Обсуждается'), ('confirmed', 'Принята'), ('declined', 'Отклонена'), ('deleted', 'Удалена')], default='pending', verbose_name='Статус')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Взнос')),
                ('payed', models.IntegerField(default=0, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('alias', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('char_id', models.CharField(max_length=100, verbose_name='char_id')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/images/', verbose_name='image')),
                ('kventa', models.FileField(blank=True, null=True, upload_to='kventas/pdf/')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонаж',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('alias', models.CharField(max_length=100, verbose_name='Алиас')),
                ('hidden', models.BooleanField(default=False, verbose_name='Секретная')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='factions/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('alias', models.CharField(max_length=20, verbose_name='Алиас')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Взнос')),
                ('player_count', models.IntegerField(blank=True, null=True, verbose_name='Количество игроков')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('open_character_list', models.BooleanField(default=False, verbose_name='Сетка открыта')),
                ('open_applications', models.BooleanField(default=False, verbose_name='Прием заявок открыт')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='VK')),
                ('tg', models.CharField(blank=True, max_length=100, null=True, verbose_name='TG')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('line', 'Строка'), ('paragraph', 'Абзац'), ('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('scale', 'Шкала'), ('matrix', 'Сетка')], default='line', verbose_name='Тип')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='Варианты')),
                ('order', models.IntegerField(default=1, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('private', models.BooleanField(default=False, verbose_name='Виден только внутри тэга')),
                ('mg', models.BooleanField(default=False, verbose_name='Виден только МГ')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
    ]
