# Generated by Django 5.1.1 on 2024-11-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='games.group', verbose_name='Фракция'),
        ),
        migrations.AddField(
            model_name='group',
            name='family',
            field=models.BooleanField(default=False, verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='character',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
    ]
