# Generated by Django 4.2.7 on 2023-12-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_character_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='character',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True, verbose_name='Варианты'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('line', 'Строка'), ('paragraph', 'Абзац'), ('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('scale', 'Шкала'), ('matrix', 'Сетка')], default='line', verbose_name='Тип'),
        ),
    ]
