# Generated by Django 4.2.7 on 2023-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_character_description_character_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/images/', verbose_name='image'),
        ),
    ]
