# Generated by Django 5.1.1 on 2024-11-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='games.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='character',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='games.group', verbose_name='Семья'),
        ),
    ]
