# Generated by Django 4.2.7 on 2023-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alias',
            field=models.CharField(default=2, max_length=100, verbose_name='Никнейм'),
            preserve_default=False,
        ),
    ]
