# Generated by Django 5.1.1 on 2024-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['order'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонаж'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
