# Generated by Django 4.2.7 on 2023-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_character_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='alias',
            field=models.CharField(default='frostpunk', max_length=20, verbose_name='Алиас'),
            preserve_default=False,
        ),
    ]
