# Generated by Django 4.2.7 on 2023-12-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Подана'), ('discussing', 'Обсуждается'), ('confirmed', 'Принята'), ('declined', 'Отклонена'), ('deleted', 'Удалена')], default='pending', verbose_name='Статус'),
        ),
    ]
