# Generated by Django 5.1.1 on 2024-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_character_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=1, verbose_name='Обязательный'),
        ),
    ]
