# Generated by Django 4.2.7 on 2023-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_answer_application_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
