# Generated by Django 5.1.1 on 2026-09-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_question_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='liked_by',
            field=models.ManyToManyField(
                blank=True,
                related_name='likes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Лайки',
            ),
        ),
    ]
