# Generated by Django 4.2.7 on 2023-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место'),
        ),
    ]
