# Generated by Django 4.2.7 on 2023-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='gray-700', max_length=10, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
