# Generated by Django 4.2.7 on 2023-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(related_name='characters', to='games.tag', verbose_name='Тэги'),
        ),
    ]
