# Generated by Django 5.0 on 2023-12-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_character_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
