# Generated by Django 5.0 on 2023-12-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_faction_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонаж'},
        ),
        migrations.AlterModelOptions(
            name='faction',
            options={'ordering': ['name'], 'verbose_name': 'Фракция', 'verbose_name_plural': 'Фракция'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='game',
            name='open_applications',
            field=models.BooleanField(default=False, verbose_name='Прием заявок открыт'),
        ),
        migrations.AddField(
            model_name='game',
            name='open_character_list',
            field=models.BooleanField(default=False, verbose_name='Сетка открыта'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Секретная'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
