# Generated by Django 5.0 on 2023-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_faction_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payed',
            field=models.IntegerField(default=0, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взнос'),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взнос'),
        ),
    ]
