# Generated by Django 5.0 on 2023-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_application_payed_application_price_game_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='tg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TG'),
        ),
        migrations.AddField(
            model_name='game',
            name='vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VK'),
        ),
    ]
