# Generated by Django 5.0.3 on 2024-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_character_kventa_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество игроков'),
        ),
    ]
